<main class='w-80 main-content  '>
     <aside class="flex flex-left align mt-1 ">
          <a href="<?php echo esc_url(site_url('/')) ?>">Internet Of Learning</a>
          [IconNext class="mh-04"]
          <a>Terms And Conditions</a>
     </aside>
     <article>
          <h3 class='text-title text-md bold'>
               Privacy Policy
          </h3>
          <p class=''>
               Internet of Learning Pte. Ltd. (“us”, “we”, or “our”) operates the https://internetoflearning.com/ website (the “Service”).
               <br />
               <br />
               This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data. We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://internetoflearning.com/

          </p>
     </article>
     <article>
          <h3 class='text-title bold text-sm '>Definitions</h3>
     </article>
     <article>
          <h3 class='text-title bold text-sm'>
               Service
          </h3>
          <p class='subtitle subtitle-xsm left'>
               Service is the https://internetoflearning.com/ website operated by Internet of Learning Pte. Ltd.
          </p>
     </article>
     <article>
          <h3 class='text-title bold text-sm'>
               Personal Data
          </h3>
          <p class='subtitle subtitle-xsm left'>
               Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
          </p>
     </article>
     <article>
          <h3 class='text-title bold text-sm'>
               Usage Data
          </h3>
          <p class='subtitle subtitle-xsm left'>
               Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
          </p>
     </article>
     <article>
          <h3 class='text-title bold text-sm'>
               Cookies
          </h3>
          <p class='subtitle subtitle-xsm left'>
               Cookies are small pieces of data stored on your device (computer or mobile device).Data Controller Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.
          </p>
     </article>
     <article>
          <h3 class='text-title bold text-sm'>
               Data Processors
          </h3>
          <p class='subtitle subtitle-xsm left'>
               Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.We may use the services of various Service Providers in order to process your data more effectively.
               <br />
               <br />
               Data Subject (or User) Data Subject is any living individual who is using our Service and is the subject of Personal Data.
          </p>
     </article>
     <article>
          <h3 class='text-title bold text-sm '>Information Collection and Use</h3>
     </article>
     <article class='flex-left'>
          <h3 class='text-title bold text-sm'>
               Personal data
          </h3>
          <p class='subtitle subtitle-xsm m-0  left'>
               While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:
          </p>
          <div>
               [List min='true' items='E-mail adress,First name and Last name, Cookies and Usage Data' icon='IconCheckMark' ]
               <p class='subtitle subtitle-xsm m-0  left'>
                    We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.
               </p>
          </div>
     </article>
     <article>
          <h3 class='text-title bold text-sm'>
               Usage Data
          </h3>
          <p class='subtitle subtitle-xsm left'>
               We may also collect information how the Service is accessed and used (“Usage Data”). This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
     </article>
     <article>
          <h3 class='text-title bold text-sm'>
               Tracking & Cookies Data
          </h3>
          <p class='subtitle subtitle-xsm left'>
               We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
          </p>
     </article>
     <div class="divider"></div>
</main>